import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

/** IDs alineados con la tabla Permission de la base de datos */
export const PERMISSIONS = [
  { id: 1, code: "admin", name: "Administrador" },
  { id: 2, code: "product.read", name: "Ver Productos" },
  { id: 3, code: "product.create", name: "Crear Producto" },
  { id: 4, code: "product.update", name: "Editar Producto" },
  { id: 5, code: "product.delete", name: "Eliminar Producto" },
  { id: 6, code: "user.read", name: "Ver Usuarios" },
  { id: 7, code: "user.create", name: "Crear Usuario" },
  { id: 8, code: "user.update", name: "Editar Usuario" },
  { id: 9, code: "user.delete", name: "Eliminar Usuario" },
  { id: 10, code: "inventory.read", name: "Ver Inventario" },
  { id: 11, code: "inventory.manage", name: "Gestionar Inventario" },
  { id: 12, code: "inventorymovement.read", name: "Ver Movimientos de Inventario" },
  { id: 13, code: "inventorymovement.create", name: "Crear Movimiento de Inventario" },
  { id: 14, code: "supplier.read", name: "Ver Proveedores" },
  { id: 15, code: "supplier.create", name: "Crear Proveedor" },
  { id: 16, code: "supplier.update", name: "Editar Proveedor" },
  { id: 17, code: "supplier.delete", name: "Eliminar Proveedor" },
  { id: 18, code: "productcategory.read", name: "Ver Categorías de Producto" },
  { id: 19, code: "productcategory.create", name: "Crear Categoría de Producto" },
  { id: 20, code: "productcategory.update", name: "Editar Categoría de Producto" },
  { id: 21, code: "productcategory.delete", name: "Eliminar Categoría de Producto" },
  { id: 22, code: "log.read", name: "Ver Registros de Actividad" },
  { id: 23, code: "setting.read", name: "Ver Configuración" },
  { id: 24, code: "setting.manage", name: "Gestionar Configuración" },
  { id: 25, code: "role.read", name: "Ver Roles" },
  { id: 26, code: "role.create", name: "Crear Rol" },
  { id: 27, code: "role.update", name: "Editar Rol" },
  { id: 28, code: "role.delete", name: "Eliminar Rol" },
  { id: 29, code: "location.read", name: "Ver Ubicaciones" },
  { id: 30, code: "location.create", name: "Crear Ubicación" },
  { id: 31, code: "location.update", name: "Editar Ubicación" },
  { id: 32, code: "location.delete", name: "Eliminar Ubicación" },
  { id: 33, code: "organization.read", name: "Ver Organizaciones" },
  { id: 34, code: "organization.create", name: "Crear Organización" },
  { id: 35, code: "organization.update", name: "Editar Organización" },
  { id: 36, code: "organization.delete", name: "Eliminar Organización" },
  { id: 105, code: "contact.read", name: "Ver Contactos" },
  { id: 106, code: "contact.create", name: "Crear Contacto" },
  { id: 107, code: "contact.update", name: "Editar Contacto" },
  { id: 108, code: "contact.delete", name: "Eliminar Contacto" },
  { id: 109, code: "lead.read", name: "Ver Leads" },
  { id: 110, code: "lead.create", name: "Crear Lead" },
  { id: 111, code: "lead.update", name: "Editar Lead" },
  { id: 112, code: "lead.delete", name: "Eliminar Lead" },
  { id: 113, code: "sale.read", name: "Ver Ventas" },
  { id: 114, code: "sale.create", name: "Crear Venta" },
  { id: 115, code: "sale.update", name: "Editar Venta" },
  { id: 116, code: "sale.cancel", name: "Cancelar Venta" },
  { id: 117, code: "sale.report", name: "Reportes de Venta" },
  { id: 118, code: "sale.return.create", name: "Crear Devolución de Venta" },
  { id: 119, code: "tag.read", name: "Ver Etiquetas" },
  { id: 120, code: "tag.create", name: "Crear Etiqueta" },
  { id: 121, code: "tag.update", name: "Editar Etiqueta" },
  { id: 122, code: "tag.delete", name: "Eliminar Etiqueta" },
  { id: 1051, code: "subscription.read", name: "Ver Suscripción" },
  { id: 1052, code: "subscription.manage", name: "Gestionar Suscripción" },
  { id: 1053, code: "plan.read", name: "Ver Planes" },
  { id: 1054, code: "plan.manage", name: "Gestionar Planes" },
  { id: 1055, code: "currency.read", name: "Ver Monedas" },
  { id: 1056, code: "currency.create", name: "Crear Moneda" },
  { id: 1057, code: "currency.update", name: "Editar Moneda" },
  { id: 1058, code: "currency.delete", name: "Eliminar Moneda" },
];
